version: '3.6'
services:
  api:
    image: node:10.15.3-alpine
    container_name: tqd-node
    build: .
    ports:
      - 3000:3000
    environment:
     - NODE_ENV=local
     - NODE_PORT=3000
     - ES_HOST=elasticsearch
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/node/app/look_for_song
    command: npm run start
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    networks: 
      - esnet
  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - esnet
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.11.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - XPACK_SECURITY_ENABLED=false
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
volumes:
  esdata:
networks:
  esnet: